version: '2'
services:
  nginx:
   container_name: my-nginx
   image: nginx:latest
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   - ./nginx/ssl:/ssl # 挂载ssl证书
   - ./nginx/web/index.html:/home/www/index.html
   - ./nginx/web/404:/home/404
   - ./app/www:/home/www # 挂载的时候注意先赋予本地挂载目录777权限
   - ./lonely-app/ftp/workdir/ftp:/home/www/files/win-ftp # 挂载ftp目录
   - ./nginx/web/icassp2020:/home/www/icassp2020
   links: 
    - code-server:code-server_v1
    - jupyter:jupyter_v1
    - portainer:portainer_v1
    - bitwardenrs:bitwardenrs_v1
  code-server:
    restart: always
    # image: codercom/code-server:3.2.0
    build: code-server/
    volumes:
      - ./app/code-server:/home/coder/project
      - ./speedup/apt-debain10.list:/etc/apt/sources.list
      - ./speedup/pip.conf:/root/.pip/pip.conf # 镜像源加速
      - db_code-server:/root/.local/share/code-server
      - python_package:/usr/local/lib/python3.7/dist-packages
      - ./code-server/setting.xml:/usr/local/apache-maven-3.6.3/conf/settings.xml
    environment: 
      - PASSWORD=511023 # code-server登录密码
    user: root
    links: 
    - jupyter:jupyter_v1
    ports: 
     - 11400:11400
     - 11401:11401
  jupyter:
    build: ./jupyter/
    restart: always
    volumes: 
      - ./app/juypter/workdir:/workdir
      - db_jupyter:/opt/conda/share/jupyter/lab # Application directory, 命令:jupyter lab path
      - ./app/juypter/lab:/home/jovyan/.jupyter/lab # User Settings directory
      - ./speedup/pip.conf:/home/jovyan/.pip/pip.conf # 镜像源加速
    user: root
    # ports: 
    #   - 8889:8888
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  bitwardenrs: # 密码管理
    restart: always
    image: bitwardenrs/server:latest
    volumes:
      - bw-data:/data/

volumes: 
  db_code-server: {}
  db_jupyter: {}
  portainer_data: {}
  bw-data: {}
  python_package: {}