version: '2'
services:
  nginx:
   container_name: my-nginx
   image: nginx:latest
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   - ./nginx/ssl:/ssl
   links: 
    - code-server:code-server_v1
    - jupyter:jupyter_v1
  code-server:
    restart: always
    # image: codercom/code-server:3.2.0
    build: code-server/
    volumes:
      - ./app/code-server:/home/coder/project
      - ./speedup/apt-debain10.list:/etc/apt/sources.list
      - ./speedup/pip.conf:/root/.pip/pip.conf # 镜像源加速
      - db_code-server:/root/.local/share/code-server
    environment: 
      - PASSWORD=511023.cc
    user: root
    # ports: 
    #  - 8089:8080
    #  - 8090:8443
  jupyter:
    build: ./jupyter/
    restart: always
    volumes: 
      - ./app/juypter/workdir:/workdir
      - db_jupyter:/opt/conda/share/jupyter/lab # Application directory, 命令:jupyter lab path
      - ./app/juypter/lab:/home/jovyan/.jupyter/lab # User Settings directory
    ports: 
      - 8889:8888
    user: root
volumes: 
  db_code-server: {}
  db_jupyter: {}