version: '2.3'
services:
#  nginx:
#   container_name: my-nginx
#   image: nginx:latest
#   restart: always
#   ports:
#   - 6008:80
#   - 443:443
#   volumes:
#   - ./nginx/conf.d:/etc/nginx/conf.d
#   - ./ssl:/ssl
#   links: 
#    - code-server:code-server_v1
  code-server:
    restart: always
    image: codercom/code-server:latest
    volumes:
      - ./app:/home/coder/project
    environment: 
      - PASSWORD=511023.cc
      - NVIDIA_VISIBLE_DEVICES=all
    user: root
    runtime: nvidia
    ports: 
     - 6008:8080
#     - 8090:8443
