version: '3.8'
services:
    v2ray_cn:
        restart: always
        image: v2ray_localbuild:v0.1 # build from Dockerfile
        volumes:
            - ./config-cn.json:/etc/v2ray/config.json
        ports: # 端口较小时需要用引号，不然无效
            - "11478:1080"
        networks: 
          - v2ray-cn
networks:
  v2ray-cn:
    driver: bridge
# docker-compose -f docker-compose-cn.yaml up -d