version: '3.8'
services:
    v2ray:
        # image: v2fly/v2fly-core # build from Dockerfile
        build: .
        volumes:
            - ./config.json:/etc/v2ray/config.json
            - ./log:/log
        ports: # 端口较小时需要用引号，不然无效
            - "1080:1080"  # socket port
            - "1087:1087"  # http port
        environment: 
            http_proxy: "http://user:password@127.0.0.1:1087"
            https_proxy: "http://user:password@127.0.0.1:1087"
        restart: always
        # deploy:
        #     replicas: 1
        #     labels: [TEST]
        #     restart_policy:
        #         condition: on-failure
        #         delay: 30s
        #         max_attempts: 5
        deploy:
            resources: 
                limits:
                    cpus: '2'
                    memory: 200M
        healthcheck:
            test: curl --silent --connect-timeout 10 http://www.google.com||exit 1
            interval: 60s
            timeout: 10s
            retries: 10
# docker stack deploy -c docker-compose.yml v2ray
