version: '3.8'
services:
    v2ray_cn:
        restart: always
        build: . # build from Dockerfile
        volumes:
            - ./config-cn.json:/etc/v2ray/config.json
            - ./log:/log
        ports: # 端口较小时需要用引号，不然无效
            - "7700:7700"
            - "7701:7701"
        networks: 
          - v2ray-cn
        environment:
          - v2ray.vmess.aead.forced=false
        command: ["run", "-c", "/etc/v2ray/config.json"]
networks:
  v2ray-cn:
    driver: bridge
# docker-compose -f docker-compose-cn.yaml up -d
