version: '3.8'
services:
    v2ray:
        image: v2ray_localbuild:v0.1 # build from Dockerfile
        # build: .
        volumes:
            - ./config.json:/etc/v2ray/config.json
            # - ./config-cn2-usa.json:/etc/v2ray/config.json
        ports: # 端口较小时需要用引号，不然无效
            - "8888:1080"
        environment: 
            http_proxy: "127.0.0.1:1080"
        deploy:
            replicas: 2
            labels: [TEST]
            restart_policy:
                condition: on-failure
                delay: 300s
                max_attempts: 5
        healthcheck:
            test: curl --silent --connect-timeout 5 http://www.google.com||exit 1
            interval: 60s
            timeout: 10s
            retries: 3
# docker stack deploy -c docker-compose.yml v2ray