version: '2.3'
services:
# 深度学习服务
  code-server:
    restart: always
    build: .
    volumes:
      - ./app:/root
    environment: 
      - PASSWORD=511023
      - NVIDIA_VISIBLE_DEVICES=all
    user: root
    runtime: nvidia
    ports: 
     - 6008:80
#     - 8090:8443
