version: '3.6'
services:
    gitlab:
        image: gitlab/gitlab-ce:13.7.8-ce.0
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                external_url 'http://chenc.icu:7001'
                gitlab_rails['gitlab_shell_ssh_port'] = 7002
                gitlab_rails['smtp_enable'] = true
                gitlab_rails['smtp_address'] = "smtp.ym.163.com"
                gitlab_rails['smtp_port'] = 465
                gitlab_rails['smtp_user_name'] = "uestc_413@163.com"
                gitlab_rails['smtp_password'] = "JPNNXVSJNGPROMMP"
                gitlab_rails['smtp_domain'] = "smtp.ym.163.com"
                gitlab_rails['smtp_authentication'] = "login"
                gitlab_rails['smtp_enable_starttls_auto'] = true
                gitlab_rails['smtp_tls'] = true
                gitlab_rails['gitlab_email_from'] = 'uestc_413@163.com'
                gitlab_rails['smtp_domain'] = "smtp.ym.163.com"
        ports:
            - '7001:80'
            - '7002:22'
        volumes:
            - gitlab_data:/var/opt/gitlab
        restart: always
volumes:
    gitlab_data: {}        
