version: '2.3'
services:
    tomcat:
        restart: always
        image: tomcat:latest
        volumes:
            - ./webapp:/usr/local/tomcat/webapps/
        ports: # 端口较小时需要用引号，不然无效
            - "8080:8080"