version: "3"
services:
    frp: 
        image: ubuntu
        volumes:
            - ./server:/server
            # - ./client:/client
        command: ["/server/frps -c /server/frps.ini"]
        entrypoint: /bin/sh -c
        # command: /client/frps -c /client/frps.ini
        network_mode: host
        restart: always
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 50M
                reservations:
                    cpus: '0.25'
                    memory: 20M