version: "3"
services:
    frp_client: 
        image: alpine
        volumes:
            # - ./server:/server
            - ./client:/client
        # command: /server/frps -c /server/frps.ini
        command: /client/frpc -c /client/frpc.ini
        network_mode: host
        restart: always
