version: '2.3'
services:
# ftp服务
  ftp-server:
    restart: always
    image: fauria/vsftpd # https://hub.docker.com/r/fauria/vsftpd
    volumes:
      - ./workdir:/home/vsftpd
    environment: 
      - FTP_USER=ftp 
      - FTP_PASS=511023
      - PASV_ADDRESS=139.9.233.236
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
      - LOCAL_UMASK=000
      - FILE_OPEN_MODE=0666
    # user: root
    ports: # 端口较小时需要用引号，不然无效
      - "20:20"
      - "21:21"
      - 21100-21110:21100-21110
