version: "3.8"
services:
  mysql8:
    image: mysql:8
    container_name: mysql-8
    volumes:
    # - ./sql/db.sql:/docker-entrypoint-initdb.d/db.sql
    - mysql8-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
    - 3306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  mysql5:
    image: mysql:5.7
    container_name: mysql-5.7
    volumes:
    # - ./sql/db.sql:/docker-entrypoint-initdb.d/db.sql
    - mysql5-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
    - 3305:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
volumes:
    mysql8-data: {}  
    mysql5-data: {} 