version: '3.8'
services: 
    visdom:
        build: .
        command: 
            -port 8097
        environment: 
            http_proxy: "http://chencx.cn:8888"
            https_proxy: "http://chencx.cn:8888"
        ports: 
            - "8097:8097"
