# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
    paths:
      - 'nginx/src/fuploads/**'
      - '.github/workflows/gradle.yml'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'nginx/src/fuploads/**'
      - '.github/workflows/gradle.yml'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nginx/src/fuploads
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: setup Gradle
      uses: gradle/gradle-build-action@v2.4.2
    - name: Run build with Gradle Wrapper
      run: ./gradlew build -x test --scan
